baseURL = "https://baremetalblog.com"
title = "Bare Metal Blog"
author = "Curtis John"
languageCode = "en"
DefaultContentLanguage = "en"
enableInlineShortcodes = true
theme = "hello-friend"
enableRobotsTXT = true
enableEmoji = true
timeout = 30000

googleAnalytics = "G-GMJQDE9153"

[params]
# The number of articles to be displayed on a single page.
paginator_pages = "5"

# Enable this if you want the archive list to be in a drop-down format.
archive_dropdown = "true"

# Default to dark mode
darkmode = "dark"

[languages]
  [languages.en]
    title = "baremetalblog"
    subtitle = ""
    keywords = ""
    copyright = ""
    menuMore = "show more"
    writtenBy = "written by"
    readMore = "read more"
    readOtherPosts = "read other posts"
    newerPosts = "newer posts"
    olderPosts = "older posts"
    minuteReadingTime = "min read"
    dateFormatSingle = "01-02-2006"
    dateFormatList = "01-02-2006"
    # leave empty to disable, enter display text to enable
    # lastModDisplay = ""

    [languages.en.params.logo]
      logoText = "baremetalblog"
      logoHomeLink = "/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "about"
        name = "about"
        url = "/about"
      [[languages.en.menu.main]]
        identifier = "contact"
        name = "contact"
        url = "/contact"

[taxonomies]
category = "categories"
tag = "tags"
archive = "archives"

[privacy]

  [privacy.vimeo]
    disabled = false
    simple = true

  [privacy.twitter]
    disabled = false
    enableDNT = true
    simple = true

  [privacy.instagram]
    disabled = true
    simple = true

  [privacy.youtube]
    disabled = false
    privacyEnhanced = true

[services]

  [services.instagram]
    disableInlineCSS = true

  [services.twitter]
    disableInlineCSS = true
