---
name: "Deploy Blog"

on:
  push:
    branches:
      - main
    paths:
      - "content/**"

jobs:
  test-changes:
    runs-on: ubuntu-22.04
    # concurrency:
    #   group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.111.3'
          extended: true

      - name: Build Hugo
        run: hugo --minify -t Blonde
  
  nix-deploy-changes:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
            submodules: true
            fetch-depth: 0

      - uses: cachix/install-nix-action@v20
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - run: nix-shell --run 'hugo version'

      - name: Build Site With nix-shell
        run: nix-shell --run 'hugo --minify -t Blonde'
