name: Docker Test Build
on: push
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag crutonjohn/baremetalblog:$(date +%s)