---
name: "Pull Request: Validate"

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    paths:
      - "nix/pkgs/**"
      - "flake.nix"
      - "content/**"

concurrency:
  group: ${{ github.head_ref }}-pr-validate
  cancel-in-progress: true

jobs:

  bump-npm:
    runs-on: ubuntu-20.04
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
            submodules: false
            fetch-depth: 0
      - uses: cachix/install-nix-action@v22
        with:
          nix_path: nixos-unstable=channel:nixos-unstable:nixpkgs=channel:nixos-unstable
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - run: nix develop --command bash -c 'node2nix -18 -i ./package.json -o ./nix/pkgs/baremetalblog/node-packages.nix -c ./nix/pkgs/baremetalblog/node.nix -e ./nix/pkgs/baremetalblog/node-env.nix'

  nix-test-derivation:
    runs-on: ubuntu-20.04
    needs: 
      - bump-npm
    steps:
      - uses: actions/checkout@v3
        with:
            submodules: false
            fetch-depth: 0
      - uses: cachix/install-nix-action@v22
        with:
          nix_path: nixos-unstable=channel:nixos-unstable:nixpkgs=channel:nixos-unstable
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Check flake output
        run: nix flake check
      - name: Build dependencies and site
        run: nix build
