---
name: "Pull Request: Validate"

on:
  pull_request:
    branches:
      - main
    paths:
      - "nix/pkgs/**"
      - "flake.nix"
      - "content/**"

concurrency:
  group: ${{ github.head_ref }}-pr-validate
  cancel-in-progress: true

jobs:
  bump-sources:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
            submodules: true
            fetch-depth: 0
      - uses: cachix/install-nix-action@v20
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - name: Update Sources
        run: nix develop --command bash -c 'niv update'
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Bump sources.nix
          branch: main
          commit_options: '--no-verify --signoff'
          file_pattern: 'nix/sources.*'
          commit_user_name: Nix Bot
          commit_author: Nix Bot <actions@github.com>
          skip_dirty_check: false
          skip_fetch: true

  bump-npm:
    runs-on: ubuntu-22.04
    needs:
      - bump-sources
    steps:
      - uses: actions/checkout@v3
        with:
            submodules: true
            fetch-depth: 0
      - uses: cachix/install-nix-action@v20
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - run: nix develop --command bash -c 'niv update'
      - run: nix develop --command bash -c 'node2nix -18 -i ./package.json -o ./nix/pkgs/baremetalblog/node-packages.nix -c ./nix/pkgs/baremetalblog/default.nix -e ./nix/pkgs/baremetalblog/node-env.nix'

  nix-test-derivation:
    runs-on: ubuntu-22.04
    needs: 
      - bump-sources
      - bump-npm
    steps:
      - uses: actions/checkout@v3
        with:
            submodules: true
            fetch-depth: 0
      - uses: cachix/install-nix-action@v20
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - run: nix develop --command bash -c 'niv update'
      - name: Build dependencies and site
        run: nix-build nix/pkgs/baremetalblog/hugo.nix

  nix-test-flake:
    runs-on: ubuntu-22.04
    needs: 
      - nix-test-derivation
      - bump-sources
      - bump-npm
    steps:
      - uses: actions/checkout@v3
        with:
            submodules: true
            fetch-depth: 0
      - uses: cachix/install-nix-action@v20
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - run: nix develop --command bash -c 'niv update'
      - name: Check build output
        run: nix build
      - name: Check flake output
        run: nix flake check
