---
name: "Pull Request: Validate"

on:
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.head_ref }}-pr-validate
  cancel-in-progress: true

jobs:
  generate-site:
    runs-on: ubuntu-22.04
    # concurrency:
    #   group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.111.3'
          extended: true

      - name: Build Hugo
        run: hugo --minify -t Blonde